export CUDA_VISIBLE_DEVICES=1
python run_conv_localhost_salesagent_neg.py --output_file  ./simulation_output/salesagent_neg_wo_dup_chitchat_e10/E_with_conv_test_u_t75.json --input_file ./data/8types_10personas_ver2_gpt4o/E.json --num-gpus 1 --max-gpu-memory 30GiB --cpu-offloading --user_temperature 0.4
python run_conv_localhost_salesagent_neg.py --output_file  ./simulation_output/salesagent_neg_wo_dup_chitchat_e10/I_with_conv_test_u_t75.json --input_file ./data/8types_10personas_ver2_gpt4o/I.json --num-gpus 1 --max-gpu-memory 30GiB --cpu-offloading --user_temperature 0.4
python run_conv_localhost_salesagent_neg.py --output_file  ./simulation_output/salesagent_neg_wo_dup_chitchat_e10/S_with_conv_test_u_t75.json --input_file ./data/8types_10personas_ver2_gpt4o/S.json --num-gpus 1 --max-gpu-memory 30GiB --cpu-offloading --user_temperature 0.4
python run_conv_localhost_salesagent_neg.py --output_file  ./simulation_output/salesagent_neg_wo_dup_chitchat_e10/N_with_conv_test_u_t75.json --input_file ./data/8types_10personas_ver2_gpt4o/N.json --num-gpus 1 --max-gpu-memory 30GiB --cpu-offloading --user_temperature 0.4
python run_conv_localhost_salesagent_neg.py --output_file  ./simulation_output/salesagent_neg_wo_dup_chitchat_e10/J_with_conv_test_u_t75.json --input_file ./data/8types_10personas_ver2_gpt4o/J.json --num-gpus 1 --max-gpu-memory 30GiB --cpu-offloading --user_temperature 0.4
python run_conv_localhost_salesagent_neg.py --output_file  ./simulation_output/salesagent_neg_wo_dup_chitchat_e10/P_with_conv_test_u_t75.json --input_file ./data/8types_10personas_ver2_gpt4o/P.json --num-gpus 1 --max-gpu-memory 30GiB --cpu-offloading --user_temperature 0.4
python run_conv_localhost_salesagent_neg.py --output_file  ./simulation_output/salesagent_neg_wo_dup_chitchat_e10/T_with_conv_test_u_t75.json --input_file ./data/8types_10personas_ver2_gpt4o/T.json --num-gpus 1 --max-gpu-memory 30GiB --cpu-offloading --user_temperature 0.4
python run_conv_localhost_salesagent_neg.py --output_file  ./simulation_output/salesagent_neg_wo_dup_chitchat_e10/F_with_conv_test_u_t75.json --input_file ./data/8types_10personas_ver2_gpt4o/F.json --num-gpus 1 --max-gpu-memory 30GiB --cpu-offloading --user_temperature 0.4
python run_conv_localhost_salesagent_neg.py --output_file  ./simulation_output/salesagent_neg_wo_dup_chitchat_e10/I_with_conv_test_u_t75.json --input_file ./data/8types_10personas_ver2_gpt4o/I.json --num-gpus 1 --max-gpu-memory 30GiB --cpu-offloading --user_temperature 0.4
