export CUDA_VISIBLE_DEVICES=0,1
python run_conv_localhost.py --output_file  ./simulation_output/salesagent_neg/E_with_conv_test_u_t75.json --input_file ./data/8types_10personas_ver2_1205_gpt4o/E.json --num-gpus 2 --max-gpu-memory 10GiB --load-8bit --cpu-offloading --user_temperature 0.75
python run_conv_localhost.py --output_file  ./simulation_output/salesagent_neg/I_with_conv_test_u_t75.json --input_file ./data/8types_10personas_ver2_gpt4o/I.json --num-gpus 2 --max-gpu-memory 10GiB --load-8bit --cpu-offloading --user_temperature 0.75
python run_conv_localhost.py --output_file  ./simulation_output/salesagent_neg/S_with_conv_test_u_t75.json --input_file ./data/8types_10personas_ver2_gpt4o/S.json --num-gpus 2 --max-gpu-memory 10GiB --load-8bit --cpu-offloading --user_temperature 0.75
python run_conv_localhost.py --output_file  ./simulation_output/salesagent_neg/N_with_conv_test_u_t75.json --input_file ./data/8types_10personas_ver2_gpt4o/N.json --num-gpus 2 --max-gpu-memory 10GiB --load-8bit --cpu-offloading --user_temperature 0.75
python run_conv_localhost.py --output_file  ./simulation_output/salesagent_neg/J_with_conv_test_u_t75.json --input_file ./data/8types_10personas_ver2_gpt4o/J.json --num-gpus 2 --max-gpu-memory 10GiB --load-8bit --cpu-offloading --user_temperature 0.75
python run_conv_localhost.py --output_file  ./simulation_output/salesagent_neg/P_with_conv_test_u_t75.json --input_file ./data/8types_10personas_ver2_gpt4o/P.json --num-gpus 2 --max-gpu-memory 10GiB --load-8bit --cpu-offloading --user_temperature 0.75
python run_conv_localhost.py --output_file  ./simulation_output/salesagent_neg/T_with_conv_test_u_t75.json --input_file ./data/8types_10personas_ver2_gpt4o/T.json --num-gpus 2 --max-gpu-memory 10GiB --load-8bit --cpu-offloading --user_temperature 0.75
python run_conv_localhost.py --output_file  ./simulation_output/salesagent_neg/F_with_conv_test_u_t75.json --input_file ./data/8types_10personas_ver2_gpt4o/F.json --num-gpus 2 --max-gpu-memory 10GiB --load-8bit --cpu-offloading --user_temperature 0.75
